/*
 * This source file was generated by the Gradle 'init' task
 */
package vscodeproject;
    class Example {
    public static void main(String[] args) {
        System.out.println("Простая программа на языке Java");
    }
}
