/*
 * This source file was generated by the Gradle 'init' task
 */
package vscodeproject;
    class Example2 {
            public static void main(String[] args) {
                int num;
                num = 100;
                System.out.println("Значение Num: " + num);
                num = num * 2;
                System.out.println("Значение num * 2: ");
                System.err.println(num);
    }
}
